## SoLoud::FFTFilter

The FFT filter is a short-time Fourier transform filter which can
be used as basis for FFT-based effects. The base implementation
does a simple tone downshifting.

The filter exists mainly to adjust the speech synthesizer's voice in
strange ways. It can also be used as basis for other FFT-based filters.
