# SoLoud wrapper for Python
# This file is autogenerated; any changes will be overwritten

from ctypes import *
soloud_dll = CDLL("soloud_x86")

# Enumerations
soloud_enum = {
"FFTFILTER_OVER": 0,
"SOLOUD_WASAPI": 6,
"SOLOUD_AUTO": 0,
"BIQUADRESONANTFILTER_NONE": 0,
"SOLOUD_CLIP_ROUNDOFF": 1,
"LOFIFILTER_BITDEPTH": 2,
"SOLOUD_SDL2": 2,
"SFXR_HURT": 4,
"FFTFILTER_MULTIPLY": 2,
"SOLOUD_ENABLE_VISUALIZATION": 2,
"BIQUADRESONANTFILTER_HIGHPASS": 2,
"SFXR_LASER": 1,
"SFXR_BLIP": 6,
"SFXR_JUMP": 5,
"LOFIFILTER_WET": 0,
"BIQUADRESONANTFILTER_WET": 0,
"LOFIFILTER_SAMPLERATE": 1,
"SOLOUD_SDL": 1,
"BIQUADRESONANTFILTER_LOWPASS": 1,
"SFXR_COIN": 0,
"FLANGERFILTER_FREQ": 2,
"SOLOUD_PORTAUDIO": 3,
"BIQUADRESONANTFILTER_SAMPLERATE": 1,
"SFXR_EXPLOSION": 2,
"BIQUADRESONANTFILTER_BANDPASS": 3,
"SOLOUD_OPENAL": 8,
"FLANGERFILTER_WET": 0,
"BIQUADRESONANTFILTER_FREQUENCY": 2,
"SFXR_POWERUP": 3,
"FFTFILTER_SUBTRACT": 1,
"SOLOUD_BACKEND_MAX": 9,
"BIQUADRESONANTFILTER_RESONANCE": 3,
"SOLOUD_XAUDIO2": 5,
"FLANGERFILTER_DELAY": 1,
"SOLOUD_WINMM": 4,
"SOLOUD_OSS": 7
}

# Functions
Soloud_destroy = soloud_dll.Soloud_destroy
Soloud_destroy.restype = None
Soloud_destroy.argtypes = [c_void_p]

Soloud_create = soloud_dll.Soloud_create
Soloud_create.restype = c_void_p
Soloud_create.argtypes = []

Soloud_init = soloud_dll.Soloud_init
Soloud_init.restype = c_int
Soloud_init.argtypes = [c_void_p]

Soloud_initEx = soloud_dll.Soloud_initEx
Soloud_initEx.restype = c_int
Soloud_initEx.argtypes = [c_void_p, c_uint, c_uint, c_uint, c_uint]

Soloud_deinit = soloud_dll.Soloud_deinit
Soloud_deinit.restype = None
Soloud_deinit.argtypes = [c_void_p]

Soloud_getVersion = soloud_dll.Soloud_getVersion
Soloud_getVersion.restype = c_uint
Soloud_getVersion.argtypes = [c_void_p]

Soloud_getErrorString = soloud_dll.Soloud_getErrorString
Soloud_getErrorString.restype = c_char_p
Soloud_getErrorString.argtypes = [c_void_p, c_int]

Soloud_play = soloud_dll.Soloud_play
Soloud_play.restype = c_uint
Soloud_play.argtypes = [c_void_p, c_void_p]

Soloud_playEx = soloud_dll.Soloud_playEx
Soloud_playEx.restype = c_uint
Soloud_playEx.argtypes = [c_void_p, c_void_p, c_float, c_float, c_int, c_uint]

Soloud_playClocked = soloud_dll.Soloud_playClocked
Soloud_playClocked.restype = c_uint
Soloud_playClocked.argtypes = [c_void_p, c_double, c_void_p]

Soloud_playClockedEx = soloud_dll.Soloud_playClockedEx
Soloud_playClockedEx.restype = c_uint
Soloud_playClockedEx.argtypes = [c_void_p, c_double, c_void_p, c_float, c_float, c_uint]

Soloud_seek = soloud_dll.Soloud_seek
Soloud_seek.restype = None
Soloud_seek.argtypes = [c_void_p, c_uint, c_double]

Soloud_stop = soloud_dll.Soloud_stop
Soloud_stop.restype = None
Soloud_stop.argtypes = [c_void_p, c_uint]

Soloud_stopAll = soloud_dll.Soloud_stopAll
Soloud_stopAll.restype = None
Soloud_stopAll.argtypes = [c_void_p]

Soloud_stopAudioSource = soloud_dll.Soloud_stopAudioSource
Soloud_stopAudioSource.restype = None
Soloud_stopAudioSource.argtypes = [c_void_p, c_void_p]

Soloud_setFilterParameter = soloud_dll.Soloud_setFilterParameter
Soloud_setFilterParameter.restype = None
Soloud_setFilterParameter.argtypes = [c_void_p, c_uint, c_uint, c_uint, c_float]

Soloud_getFilterParameter = soloud_dll.Soloud_getFilterParameter
Soloud_getFilterParameter.restype = c_float
Soloud_getFilterParameter.argtypes = [c_void_p, c_uint, c_uint, c_uint]

Soloud_fadeFilterParameter = soloud_dll.Soloud_fadeFilterParameter
Soloud_fadeFilterParameter.restype = None
Soloud_fadeFilterParameter.argtypes = [c_void_p, c_uint, c_uint, c_uint, c_float, c_double]

Soloud_oscillateFilterParameter = soloud_dll.Soloud_oscillateFilterParameter
Soloud_oscillateFilterParameter.restype = None
Soloud_oscillateFilterParameter.argtypes = [c_void_p, c_uint, c_uint, c_uint, c_float, c_float, c_double]

Soloud_getStreamTime = soloud_dll.Soloud_getStreamTime
Soloud_getStreamTime.restype = c_double
Soloud_getStreamTime.argtypes = [c_void_p, c_uint]

Soloud_getPause = soloud_dll.Soloud_getPause
Soloud_getPause.restype = c_int
Soloud_getPause.argtypes = [c_void_p, c_uint]

Soloud_getVolume = soloud_dll.Soloud_getVolume
Soloud_getVolume.restype = c_float
Soloud_getVolume.argtypes = [c_void_p, c_uint]

Soloud_getPan = soloud_dll.Soloud_getPan
Soloud_getPan.restype = c_float
Soloud_getPan.argtypes = [c_void_p, c_uint]

Soloud_getSamplerate = soloud_dll.Soloud_getSamplerate
Soloud_getSamplerate.restype = c_float
Soloud_getSamplerate.argtypes = [c_void_p, c_uint]

Soloud_getProtectVoice = soloud_dll.Soloud_getProtectVoice
Soloud_getProtectVoice.restype = c_int
Soloud_getProtectVoice.argtypes = [c_void_p, c_uint]

Soloud_getActiveVoiceCount = soloud_dll.Soloud_getActiveVoiceCount
Soloud_getActiveVoiceCount.restype = c_uint
Soloud_getActiveVoiceCount.argtypes = [c_void_p]

Soloud_isValidVoiceHandle = soloud_dll.Soloud_isValidVoiceHandle
Soloud_isValidVoiceHandle.restype = c_int
Soloud_isValidVoiceHandle.argtypes = [c_void_p, c_uint]

Soloud_getRelativePlaySpeed = soloud_dll.Soloud_getRelativePlaySpeed
Soloud_getRelativePlaySpeed.restype = c_float
Soloud_getRelativePlaySpeed.argtypes = [c_void_p, c_uint]

Soloud_getPostClipScaler = soloud_dll.Soloud_getPostClipScaler
Soloud_getPostClipScaler.restype = c_float
Soloud_getPostClipScaler.argtypes = [c_void_p]

Soloud_getGlobalVolume = soloud_dll.Soloud_getGlobalVolume
Soloud_getGlobalVolume.restype = c_float
Soloud_getGlobalVolume.argtypes = [c_void_p]

Soloud_setGlobalVolume = soloud_dll.Soloud_setGlobalVolume
Soloud_setGlobalVolume.restype = None
Soloud_setGlobalVolume.argtypes = [c_void_p, c_float]

Soloud_setPostClipScaler = soloud_dll.Soloud_setPostClipScaler
Soloud_setPostClipScaler.restype = None
Soloud_setPostClipScaler.argtypes = [c_void_p, c_float]

Soloud_setPause = soloud_dll.Soloud_setPause
Soloud_setPause.restype = None
Soloud_setPause.argtypes = [c_void_p, c_uint, c_int]

Soloud_setPauseAll = soloud_dll.Soloud_setPauseAll
Soloud_setPauseAll.restype = None
Soloud_setPauseAll.argtypes = [c_void_p, c_int]

Soloud_setRelativePlaySpeed = soloud_dll.Soloud_setRelativePlaySpeed
Soloud_setRelativePlaySpeed.restype = None
Soloud_setRelativePlaySpeed.argtypes = [c_void_p, c_uint, c_float]

Soloud_setProtectVoice = soloud_dll.Soloud_setProtectVoice
Soloud_setProtectVoice.restype = None
Soloud_setProtectVoice.argtypes = [c_void_p, c_uint, c_int]

Soloud_setSamplerate = soloud_dll.Soloud_setSamplerate
Soloud_setSamplerate.restype = None
Soloud_setSamplerate.argtypes = [c_void_p, c_uint, c_float]

Soloud_setPan = soloud_dll.Soloud_setPan
Soloud_setPan.restype = None
Soloud_setPan.argtypes = [c_void_p, c_uint, c_float]

Soloud_setPanAbsolute = soloud_dll.Soloud_setPanAbsolute
Soloud_setPanAbsolute.restype = None
Soloud_setPanAbsolute.argtypes = [c_void_p, c_uint, c_float, c_float]

Soloud_setVolume = soloud_dll.Soloud_setVolume
Soloud_setVolume.restype = None
Soloud_setVolume.argtypes = [c_void_p, c_uint, c_float]

Soloud_setDelaySamples = soloud_dll.Soloud_setDelaySamples
Soloud_setDelaySamples.restype = None
Soloud_setDelaySamples.argtypes = [c_void_p, c_uint, c_uint]

Soloud_fadeVolume = soloud_dll.Soloud_fadeVolume
Soloud_fadeVolume.restype = None
Soloud_fadeVolume.argtypes = [c_void_p, c_uint, c_float, c_double]

Soloud_fadePan = soloud_dll.Soloud_fadePan
Soloud_fadePan.restype = None
Soloud_fadePan.argtypes = [c_void_p, c_uint, c_float, c_double]

Soloud_fadeRelativePlaySpeed = soloud_dll.Soloud_fadeRelativePlaySpeed
Soloud_fadeRelativePlaySpeed.restype = None
Soloud_fadeRelativePlaySpeed.argtypes = [c_void_p, c_uint, c_float, c_double]

Soloud_fadeGlobalVolume = soloud_dll.Soloud_fadeGlobalVolume
Soloud_fadeGlobalVolume.restype = None
Soloud_fadeGlobalVolume.argtypes = [c_void_p, c_float, c_double]

Soloud_schedulePause = soloud_dll.Soloud_schedulePause
Soloud_schedulePause.restype = None
Soloud_schedulePause.argtypes = [c_void_p, c_uint, c_double]

Soloud_scheduleStop = soloud_dll.Soloud_scheduleStop
Soloud_scheduleStop.restype = None
Soloud_scheduleStop.argtypes = [c_void_p, c_uint, c_double]

Soloud_oscillateVolume = soloud_dll.Soloud_oscillateVolume
Soloud_oscillateVolume.restype = None
Soloud_oscillateVolume.argtypes = [c_void_p, c_uint, c_float, c_float, c_double]

Soloud_oscillatePan = soloud_dll.Soloud_oscillatePan
Soloud_oscillatePan.restype = None
Soloud_oscillatePan.argtypes = [c_void_p, c_uint, c_float, c_float, c_double]

Soloud_oscillateRelativePlaySpeed = soloud_dll.Soloud_oscillateRelativePlaySpeed
Soloud_oscillateRelativePlaySpeed.restype = None
Soloud_oscillateRelativePlaySpeed.argtypes = [c_void_p, c_uint, c_float, c_float, c_double]

Soloud_oscillateGlobalVolume = soloud_dll.Soloud_oscillateGlobalVolume
Soloud_oscillateGlobalVolume.restype = None
Soloud_oscillateGlobalVolume.argtypes = [c_void_p, c_float, c_float, c_double]

Soloud_setGlobalFilter = soloud_dll.Soloud_setGlobalFilter
Soloud_setGlobalFilter.restype = None
Soloud_setGlobalFilter.argtypes = [c_void_p, c_uint, c_void_p]

Soloud_setVisualizationEnable = soloud_dll.Soloud_setVisualizationEnable
Soloud_setVisualizationEnable.restype = None
Soloud_setVisualizationEnable.argtypes = [c_void_p, c_int]

Soloud_calcFFT = soloud_dll.Soloud_calcFFT
Soloud_calcFFT.restype = POINTER(c_float * 256)
Soloud_calcFFT.argtypes = [c_void_p]

Soloud_getWave = soloud_dll.Soloud_getWave
Soloud_getWave.restype = POINTER(c_float * 256)
Soloud_getWave.argtypes = [c_void_p]

Soloud_getLoopCount = soloud_dll.Soloud_getLoopCount
Soloud_getLoopCount.restype = c_uint
Soloud_getLoopCount.argtypes = [c_void_p, c_uint]

Soloud_createVoiceGroup = soloud_dll.Soloud_createVoiceGroup
Soloud_createVoiceGroup.restype = c_uint
Soloud_createVoiceGroup.argtypes = [c_void_p]

Soloud_destroyVoiceGroup = soloud_dll.Soloud_destroyVoiceGroup
Soloud_destroyVoiceGroup.restype = c_int
Soloud_destroyVoiceGroup.argtypes = [c_void_p, c_uint]

Soloud_addVoiceToGroup = soloud_dll.Soloud_addVoiceToGroup
Soloud_addVoiceToGroup.restype = c_int
Soloud_addVoiceToGroup.argtypes = [c_void_p, c_uint, c_uint]

Soloud_isVoiceGroup = soloud_dll.Soloud_isVoiceGroup
Soloud_isVoiceGroup.restype = c_int
Soloud_isVoiceGroup.argtypes = [c_void_p, c_uint]

Soloud_isVoiceGroupEmpty = soloud_dll.Soloud_isVoiceGroupEmpty
Soloud_isVoiceGroupEmpty.restype = c_int
Soloud_isVoiceGroupEmpty.argtypes = [c_void_p, c_uint]

BiquadResonantFilter_destroy = soloud_dll.BiquadResonantFilter_destroy
BiquadResonantFilter_destroy.restype = None
BiquadResonantFilter_destroy.argtypes = [c_void_p]

BiquadResonantFilter_create = soloud_dll.BiquadResonantFilter_create
BiquadResonantFilter_create.restype = c_void_p
BiquadResonantFilter_create.argtypes = []

BiquadResonantFilter_setParams = soloud_dll.BiquadResonantFilter_setParams
BiquadResonantFilter_setParams.restype = c_int
BiquadResonantFilter_setParams.argtypes = [c_void_p, c_int, c_float, c_float, c_float]

Bus_destroy = soloud_dll.Bus_destroy
Bus_destroy.restype = None
Bus_destroy.argtypes = [c_void_p]

Bus_create = soloud_dll.Bus_create
Bus_create.restype = c_void_p
Bus_create.argtypes = []

Bus_setFilter = soloud_dll.Bus_setFilter
Bus_setFilter.restype = None
Bus_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

Bus_play = soloud_dll.Bus_play
Bus_play.restype = c_uint
Bus_play.argtypes = [c_void_p, c_void_p]

Bus_playEx = soloud_dll.Bus_playEx
Bus_playEx.restype = c_uint
Bus_playEx.argtypes = [c_void_p, c_void_p, c_float, c_float, c_int]

Bus_playClocked = soloud_dll.Bus_playClocked
Bus_playClocked.restype = c_uint
Bus_playClocked.argtypes = [c_void_p, c_double, c_void_p]

Bus_playClockedEx = soloud_dll.Bus_playClockedEx
Bus_playClockedEx.restype = c_uint
Bus_playClockedEx.argtypes = [c_void_p, c_double, c_void_p, c_float, c_float]

Bus_setVisualizationEnable = soloud_dll.Bus_setVisualizationEnable
Bus_setVisualizationEnable.restype = None
Bus_setVisualizationEnable.argtypes = [c_void_p, c_int]

Bus_calcFFT = soloud_dll.Bus_calcFFT
Bus_calcFFT.restype = POINTER(c_float * 256)
Bus_calcFFT.argtypes = [c_void_p]

Bus_getWave = soloud_dll.Bus_getWave
Bus_getWave.restype = POINTER(c_float * 256)
Bus_getWave.argtypes = [c_void_p]

Bus_setLooping = soloud_dll.Bus_setLooping
Bus_setLooping.restype = None
Bus_setLooping.argtypes = [c_void_p, c_int]

Bus_stop = soloud_dll.Bus_stop
Bus_stop.restype = None
Bus_stop.argtypes = [c_void_p]

EchoFilter_destroy = soloud_dll.EchoFilter_destroy
EchoFilter_destroy.restype = None
EchoFilter_destroy.argtypes = [c_void_p]

EchoFilter_create = soloud_dll.EchoFilter_create
EchoFilter_create.restype = c_void_p
EchoFilter_create.argtypes = []

EchoFilter_setParams = soloud_dll.EchoFilter_setParams
EchoFilter_setParams.restype = c_int
EchoFilter_setParams.argtypes = [c_void_p, c_float]

EchoFilter_setParamsEx = soloud_dll.EchoFilter_setParamsEx
EchoFilter_setParamsEx.restype = c_int
EchoFilter_setParamsEx.argtypes = [c_void_p, c_float, c_float, c_float]

FFTFilter_destroy = soloud_dll.FFTFilter_destroy
FFTFilter_destroy.restype = None
FFTFilter_destroy.argtypes = [c_void_p]

FFTFilter_create = soloud_dll.FFTFilter_create
FFTFilter_create.restype = c_void_p
FFTFilter_create.argtypes = []

FFTFilter_setParameters = soloud_dll.FFTFilter_setParameters
FFTFilter_setParameters.restype = c_int
FFTFilter_setParameters.argtypes = [c_void_p, c_int]

FFTFilter_setParametersEx = soloud_dll.FFTFilter_setParametersEx
FFTFilter_setParametersEx.restype = c_int
FFTFilter_setParametersEx.argtypes = [c_void_p, c_int, c_int, c_float]

FlangerFilter_destroy = soloud_dll.FlangerFilter_destroy
FlangerFilter_destroy.restype = None
FlangerFilter_destroy.argtypes = [c_void_p]

FlangerFilter_create = soloud_dll.FlangerFilter_create
FlangerFilter_create.restype = c_void_p
FlangerFilter_create.argtypes = []

FlangerFilter_setParams = soloud_dll.FlangerFilter_setParams
FlangerFilter_setParams.restype = c_int
FlangerFilter_setParams.argtypes = [c_void_p, c_float, c_float]

LofiFilter_destroy = soloud_dll.LofiFilter_destroy
LofiFilter_destroy.restype = None
LofiFilter_destroy.argtypes = [c_void_p]

LofiFilter_create = soloud_dll.LofiFilter_create
LofiFilter_create.restype = c_void_p
LofiFilter_create.argtypes = []

LofiFilter_setParams = soloud_dll.LofiFilter_setParams
LofiFilter_setParams.restype = c_int
LofiFilter_setParams.argtypes = [c_void_p, c_float, c_float]

Modplug_destroy = soloud_dll.Modplug_destroy
Modplug_destroy.restype = None
Modplug_destroy.argtypes = [c_void_p]

Modplug_create = soloud_dll.Modplug_create
Modplug_create.restype = c_void_p
Modplug_create.argtypes = []

Modplug_load = soloud_dll.Modplug_load
Modplug_load.restype = c_int
Modplug_load.argtypes = [c_void_p, c_char_p]

Modplug_setLooping = soloud_dll.Modplug_setLooping
Modplug_setLooping.restype = None
Modplug_setLooping.argtypes = [c_void_p, c_int]

Modplug_setFilter = soloud_dll.Modplug_setFilter
Modplug_setFilter.restype = None
Modplug_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

Modplug_stop = soloud_dll.Modplug_stop
Modplug_stop.restype = None
Modplug_stop.argtypes = [c_void_p]

Prg_destroy = soloud_dll.Prg_destroy
Prg_destroy.restype = None
Prg_destroy.argtypes = [c_void_p]

Prg_create = soloud_dll.Prg_create
Prg_create.restype = c_void_p
Prg_create.argtypes = []

Prg_rand = soloud_dll.Prg_rand
Prg_rand.restype = c_uint
Prg_rand.argtypes = [c_void_p]

Prg_srand = soloud_dll.Prg_srand
Prg_srand.restype = None
Prg_srand.argtypes = [c_void_p, c_int]

Sfxr_destroy = soloud_dll.Sfxr_destroy
Sfxr_destroy.restype = None
Sfxr_destroy.argtypes = [c_void_p]

Sfxr_create = soloud_dll.Sfxr_create
Sfxr_create.restype = c_void_p
Sfxr_create.argtypes = []

Sfxr_resetParams = soloud_dll.Sfxr_resetParams
Sfxr_resetParams.restype = None
Sfxr_resetParams.argtypes = [c_void_p]

Sfxr_loadParams = soloud_dll.Sfxr_loadParams
Sfxr_loadParams.restype = c_int
Sfxr_loadParams.argtypes = [c_void_p, c_char_p]

Sfxr_loadPreset = soloud_dll.Sfxr_loadPreset
Sfxr_loadPreset.restype = c_int
Sfxr_loadPreset.argtypes = [c_void_p, c_int, c_int]

Sfxr_setLooping = soloud_dll.Sfxr_setLooping
Sfxr_setLooping.restype = None
Sfxr_setLooping.argtypes = [c_void_p, c_int]

Sfxr_setFilter = soloud_dll.Sfxr_setFilter
Sfxr_setFilter.restype = None
Sfxr_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

Sfxr_stop = soloud_dll.Sfxr_stop
Sfxr_stop.restype = None
Sfxr_stop.argtypes = [c_void_p]

Speech_destroy = soloud_dll.Speech_destroy
Speech_destroy.restype = None
Speech_destroy.argtypes = [c_void_p]

Speech_create = soloud_dll.Speech_create
Speech_create.restype = c_void_p
Speech_create.argtypes = []

Speech_setText = soloud_dll.Speech_setText
Speech_setText.restype = c_int
Speech_setText.argtypes = [c_void_p, c_char_p]

Speech_setLooping = soloud_dll.Speech_setLooping
Speech_setLooping.restype = None
Speech_setLooping.argtypes = [c_void_p, c_int]

Speech_setFilter = soloud_dll.Speech_setFilter
Speech_setFilter.restype = None
Speech_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

Speech_stop = soloud_dll.Speech_stop
Speech_stop.restype = None
Speech_stop.argtypes = [c_void_p]

Wav_destroy = soloud_dll.Wav_destroy
Wav_destroy.restype = None
Wav_destroy.argtypes = [c_void_p]

Wav_create = soloud_dll.Wav_create
Wav_create.restype = c_void_p
Wav_create.argtypes = []

Wav_load = soloud_dll.Wav_load
Wav_load.restype = c_int
Wav_load.argtypes = [c_void_p, c_char_p]

Wav_loadMem = soloud_dll.Wav_loadMem
Wav_loadMem.restype = c_int
Wav_loadMem.argtypes = [c_void_p, POINTER(c_ubyte), c_uint]

Wav_getLength = soloud_dll.Wav_getLength
Wav_getLength.restype = c_double
Wav_getLength.argtypes = [c_void_p]

Wav_setLooping = soloud_dll.Wav_setLooping
Wav_setLooping.restype = None
Wav_setLooping.argtypes = [c_void_p, c_int]

Wav_setFilter = soloud_dll.Wav_setFilter
Wav_setFilter.restype = None
Wav_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

Wav_stop = soloud_dll.Wav_stop
Wav_stop.restype = None
Wav_stop.argtypes = [c_void_p]

WavStream_destroy = soloud_dll.WavStream_destroy
WavStream_destroy.restype = None
WavStream_destroy.argtypes = [c_void_p]

WavStream_create = soloud_dll.WavStream_create
WavStream_create.restype = c_void_p
WavStream_create.argtypes = []

WavStream_load = soloud_dll.WavStream_load
WavStream_load.restype = c_int
WavStream_load.argtypes = [c_void_p, c_char_p]

WavStream_getLength = soloud_dll.WavStream_getLength
WavStream_getLength.restype = c_double
WavStream_getLength.argtypes = [c_void_p]

WavStream_setLooping = soloud_dll.WavStream_setLooping
WavStream_setLooping.restype = None
WavStream_setLooping.argtypes = [c_void_p, c_int]

WavStream_setFilter = soloud_dll.WavStream_setFilter
WavStream_setFilter.restype = None
WavStream_setFilter.argtypes = [c_void_p, c_uint, c_void_p]

WavStream_stop = soloud_dll.WavStream_stop
WavStream_stop.restype = None
WavStream_stop.argtypes = [c_void_p]

# OOP wrappers

class Soloud(object):
	WASAPI = 6
	AUTO = 0
	CLIP_ROUNDOFF = 1
	SDL2 = 2
	ENABLE_VISUALIZATION = 2
	SDL = 1
	PORTAUDIO = 3
	OPENAL = 8
	BACKEND_MAX = 9
	XAUDIO2 = 5
	WINMM = 4
	OSS = 7
	def __init__(self):
		self.objhandle = Soloud_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Soloud_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Soloud_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Soloud_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Soloud_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def init(self):
		return Soloud_init(self.objhandle)
	def init_ex(self, aFlags = CLIP_ROUNDOFF, aBackend = AUTO, aSamplerate = AUTO, aBufferSize = AUTO):
		return Soloud_initEx(self.objhandle, c_uint(aFlags), c_uint(aBackend), c_uint(aSamplerate), c_uint(aBufferSize))
	def deinit(self):
		Soloud_deinit(self.objhandle)
	def get_version(self):
		return Soloud_getVersion(self.objhandle)
	def get_error_string(self, aErrorCode):
		return Soloud_getErrorString(self.objhandle, c_int(aErrorCode))
	def play(self, aSound):
		return Soloud_play(self.objhandle, aSound.objhandle)
	def play_ex(self, aSound, aVolume = 1.0, aPan = 0.0, aPaused = 0, aBus = 0):
		return Soloud_playEx(self.objhandle, aSound.objhandle, c_float(aVolume), c_float(aPan), c_int(aPaused), c_uint(aBus))
	def play_clocked(self, aSoundTime, aSound):
		return Soloud_playClocked(self.objhandle, c_double(aSoundTime), aSound.objhandle)
	def play_clocked_ex(self, aSoundTime, aSound, aVolume = 1.0, aPan = 0.0, aBus = 0):
		return Soloud_playClockedEx(self.objhandle, c_double(aSoundTime), aSound.objhandle, c_float(aVolume), c_float(aPan), c_uint(aBus))
	def seek(self, aVoiceHandle, aSeconds):
		Soloud_seek(self.objhandle, c_uint(aVoiceHandle), c_double(aSeconds))
	def stop(self, aVoiceHandle):
		Soloud_stop(self.objhandle, c_uint(aVoiceHandle))
	def stop_all(self):
		Soloud_stopAll(self.objhandle)
	def stop_audio_source(self, aSound):
		Soloud_stopAudioSource(self.objhandle, aSound.objhandle)
	def set_filter_parameter(self, aVoiceHandle, aFilterId, aAttributeId, aValue):
		Soloud_setFilterParameter(self.objhandle, c_uint(aVoiceHandle), c_uint(aFilterId), c_uint(aAttributeId), c_float(aValue))
	def get_filter_parameter(self, aVoiceHandle, aFilterId, aAttributeId):
		return Soloud_getFilterParameter(self.objhandle, c_uint(aVoiceHandle), c_uint(aFilterId), c_uint(aAttributeId))
	def fade_filter_parameter(self, aVoiceHandle, aFilterId, aAttributeId, aTo, aTime):
		Soloud_fadeFilterParameter(self.objhandle, c_uint(aVoiceHandle), c_uint(aFilterId), c_uint(aAttributeId), c_float(aTo), c_double(aTime))
	def oscillate_filter_parameter(self, aVoiceHandle, aFilterId, aAttributeId, aFrom, aTo, aTime):
		Soloud_oscillateFilterParameter(self.objhandle, c_uint(aVoiceHandle), c_uint(aFilterId), c_uint(aAttributeId), c_float(aFrom), c_float(aTo), c_double(aTime))
	def get_stream_time(self, aVoiceHandle):
		return Soloud_getStreamTime(self.objhandle, c_uint(aVoiceHandle))
	def get_pause(self, aVoiceHandle):
		return Soloud_getPause(self.objhandle, c_uint(aVoiceHandle))
	def get_volume(self, aVoiceHandle):
		return Soloud_getVolume(self.objhandle, c_uint(aVoiceHandle))
	def get_pan(self, aVoiceHandle):
		return Soloud_getPan(self.objhandle, c_uint(aVoiceHandle))
	def get_samplerate(self, aVoiceHandle):
		return Soloud_getSamplerate(self.objhandle, c_uint(aVoiceHandle))
	def get_protect_voice(self, aVoiceHandle):
		return Soloud_getProtectVoice(self.objhandle, c_uint(aVoiceHandle))
	def get_active_voice_count(self):
		return Soloud_getActiveVoiceCount(self.objhandle)
	def is_valid_voice_handle(self, aVoiceHandle):
		return Soloud_isValidVoiceHandle(self.objhandle, c_uint(aVoiceHandle))
	def get_relative_play_speed(self, aVoiceHandle):
		return Soloud_getRelativePlaySpeed(self.objhandle, c_uint(aVoiceHandle))
	def get_post_clip_scaler(self):
		return Soloud_getPostClipScaler(self.objhandle)
	def get_global_volume(self):
		return Soloud_getGlobalVolume(self.objhandle)
	def set_global_volume(self, aVolume):
		Soloud_setGlobalVolume(self.objhandle, c_float(aVolume))
	def set_post_clip_scaler(self, aScaler):
		Soloud_setPostClipScaler(self.objhandle, c_float(aScaler))
	def set_pause(self, aVoiceHandle, aPause):
		Soloud_setPause(self.objhandle, c_uint(aVoiceHandle), c_int(aPause))
	def set_pause_all(self, aPause):
		Soloud_setPauseAll(self.objhandle, c_int(aPause))
	def set_relative_play_speed(self, aVoiceHandle, aSpeed):
		Soloud_setRelativePlaySpeed(self.objhandle, c_uint(aVoiceHandle), c_float(aSpeed))
	def set_protect_voice(self, aVoiceHandle, aProtect):
		Soloud_setProtectVoice(self.objhandle, c_uint(aVoiceHandle), c_int(aProtect))
	def set_samplerate(self, aVoiceHandle, aSamplerate):
		Soloud_setSamplerate(self.objhandle, c_uint(aVoiceHandle), c_float(aSamplerate))
	def set_pan(self, aVoiceHandle, aPan):
		Soloud_setPan(self.objhandle, c_uint(aVoiceHandle), c_float(aPan))
	def set_pan_absolute(self, aVoiceHandle, aLVolume, aRVolume):
		Soloud_setPanAbsolute(self.objhandle, c_uint(aVoiceHandle), c_float(aLVolume), c_float(aRVolume))
	def set_volume(self, aVoiceHandle, aVolume):
		Soloud_setVolume(self.objhandle, c_uint(aVoiceHandle), c_float(aVolume))
	def set_delay_samples(self, aVoiceHandle, aSamples):
		Soloud_setDelaySamples(self.objhandle, c_uint(aVoiceHandle), c_uint(aSamples))
	def fade_volume(self, aVoiceHandle, aTo, aTime):
		Soloud_fadeVolume(self.objhandle, c_uint(aVoiceHandle), c_float(aTo), c_double(aTime))
	def fade_pan(self, aVoiceHandle, aTo, aTime):
		Soloud_fadePan(self.objhandle, c_uint(aVoiceHandle), c_float(aTo), c_double(aTime))
	def fade_relative_play_speed(self, aVoiceHandle, aTo, aTime):
		Soloud_fadeRelativePlaySpeed(self.objhandle, c_uint(aVoiceHandle), c_float(aTo), c_double(aTime))
	def fade_global_volume(self, aTo, aTime):
		Soloud_fadeGlobalVolume(self.objhandle, c_float(aTo), c_double(aTime))
	def schedule_pause(self, aVoiceHandle, aTime):
		Soloud_schedulePause(self.objhandle, c_uint(aVoiceHandle), c_double(aTime))
	def schedule_stop(self, aVoiceHandle, aTime):
		Soloud_scheduleStop(self.objhandle, c_uint(aVoiceHandle), c_double(aTime))
	def oscillate_volume(self, aVoiceHandle, aFrom, aTo, aTime):
		Soloud_oscillateVolume(self.objhandle, c_uint(aVoiceHandle), c_float(aFrom), c_float(aTo), c_double(aTime))
	def oscillate_pan(self, aVoiceHandle, aFrom, aTo, aTime):
		Soloud_oscillatePan(self.objhandle, c_uint(aVoiceHandle), c_float(aFrom), c_float(aTo), c_double(aTime))
	def oscillate_relative_play_speed(self, aVoiceHandle, aFrom, aTo, aTime):
		Soloud_oscillateRelativePlaySpeed(self.objhandle, c_uint(aVoiceHandle), c_float(aFrom), c_float(aTo), c_double(aTime))
	def oscillate_global_volume(self, aFrom, aTo, aTime):
		Soloud_oscillateGlobalVolume(self.objhandle, c_float(aFrom), c_float(aTo), c_double(aTime))
	def set_global_filter(self, aFilterId, aFilter):
		Soloud_setGlobalFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def set_visualization_enable(self, aEnable):
		Soloud_setVisualizationEnable(self.objhandle, c_int(aEnable))
	def calc_fft(self):
		floatbuf = Soloud_calcFFT(self.objhandle)
		return [f for f in floatbuf.contents]
	def get_wave(self):
		floatbuf = Soloud_getWave(self.objhandle)
		return [f for f in floatbuf.contents]
	def get_loop_count(self, aVoiceHandle):
		return Soloud_getLoopCount(self.objhandle, c_uint(aVoiceHandle))
	def create_voice_group(self):
		return Soloud_createVoiceGroup(self.objhandle)
	def destroy_voice_group(self, aVoiceGroupHandle):
		return Soloud_destroyVoiceGroup(self.objhandle, c_uint(aVoiceGroupHandle))
	def add_voice_to_group(self, aVoiceGroupHandle, aVoiceHandle):
		return Soloud_addVoiceToGroup(self.objhandle, c_uint(aVoiceGroupHandle), c_uint(aVoiceHandle))
	def is_voice_group(self, aVoiceGroupHandle):
		return Soloud_isVoiceGroup(self.objhandle, c_uint(aVoiceGroupHandle))
	def is_voice_group_empty(self, aVoiceGroupHandle):
		return Soloud_isVoiceGroupEmpty(self.objhandle, c_uint(aVoiceGroupHandle))

class BiquadResonantFilter(object):
	NONE = 0
	HIGHPASS = 2
	WET = 0
	LOWPASS = 1
	SAMPLERATE = 1
	BANDPASS = 3
	FREQUENCY = 2
	RESONANCE = 3
	def __init__(self):
		self.objhandle = BiquadResonantFilter_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		BiquadResonantFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		BiquadResonantFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		BiquadResonantFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		BiquadResonantFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_params(self, aType, aSampleRate, aFrequency, aResonance):
		return BiquadResonantFilter_setParams(self.objhandle, c_int(aType), c_float(aSampleRate), c_float(aFrequency), c_float(aResonance))

class Bus(object):
	def __init__(self):
		self.objhandle = Bus_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Bus_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Bus_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Bus_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Bus_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_filter(self, aFilterId, aFilter):
		Bus_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def play(self, aSound):
		return Bus_play(self.objhandle, aSound.objhandle)
	def play_ex(self, aSound, aVolume = 1.0, aPan = 0.0, aPaused = 0):
		return Bus_playEx(self.objhandle, aSound.objhandle, c_float(aVolume), c_float(aPan), c_int(aPaused))
	def play_clocked(self, aSoundTime, aSound):
		return Bus_playClocked(self.objhandle, c_double(aSoundTime), aSound.objhandle)
	def play_clocked_ex(self, aSoundTime, aSound, aVolume = 1.0, aPan = 0.0):
		return Bus_playClockedEx(self.objhandle, c_double(aSoundTime), aSound.objhandle, c_float(aVolume), c_float(aPan))
	def set_visualization_enable(self, aEnable):
		Bus_setVisualizationEnable(self.objhandle, c_int(aEnable))
	def calc_fft(self):
		floatbuf = Bus_calcFFT(self.objhandle)
		return [f for f in floatbuf.contents]
	def get_wave(self):
		floatbuf = Bus_getWave(self.objhandle)
		return [f for f in floatbuf.contents]
	def set_looping(self, aLoop):
		Bus_setLooping(self.objhandle, c_int(aLoop))
	def stop(self):
		Bus_stop(self.objhandle)

class EchoFilter(object):
	def __init__(self):
		self.objhandle = EchoFilter_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		EchoFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		EchoFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		EchoFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		EchoFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_params(self, aDelay):
		return EchoFilter_setParams(self.objhandle, c_float(aDelay))
	def set_params_ex(self, aDelay, aDecay = 0.7, aFilter = 0.0):
		return EchoFilter_setParamsEx(self.objhandle, c_float(aDelay), c_float(aDecay), c_float(aFilter))

class FFTFilter(object):
	OVER = 0
	MULTIPLY = 2
	SUBTRACT = 1
	def __init__(self):
		self.objhandle = FFTFilter_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		FFTFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		FFTFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		FFTFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		FFTFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_parameters(self, aShift):
		return FFTFilter_setParameters(self.objhandle, c_int(aShift))
	def set_parameters_ex(self, aShift, aCombine = 0, aScale = 0.002):
		return FFTFilter_setParametersEx(self.objhandle, c_int(aShift), c_int(aCombine), c_float(aScale))

class FlangerFilter(object):
	FREQ = 2
	WET = 0
	DELAY = 1
	def __init__(self):
		self.objhandle = FlangerFilter_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		FlangerFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		FlangerFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		FlangerFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		FlangerFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_params(self, aDelay, aFreq):
		return FlangerFilter_setParams(self.objhandle, c_float(aDelay), c_float(aFreq))

class LofiFilter(object):
	BITDEPTH = 2
	WET = 0
	SAMPLERATE = 1
	def __init__(self):
		self.objhandle = LofiFilter_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		LofiFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		LofiFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		LofiFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		LofiFilter_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_params(self, aSampleRate, aBitdepth):
		return LofiFilter_setParams(self.objhandle, c_float(aSampleRate), c_float(aBitdepth))

class Modplug(object):
	def __init__(self):
		self.objhandle = Modplug_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Modplug_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Modplug_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Modplug_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Modplug_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def load(self, aFilename):
		return Modplug_load(self.objhandle, c_char_p(aFilename))
	def set_looping(self, aLoop):
		Modplug_setLooping(self.objhandle, c_int(aLoop))
	def set_filter(self, aFilterId, aFilter):
		Modplug_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def stop(self):
		Modplug_stop(self.objhandle)

class Prg(object):
	def __init__(self):
		self.objhandle = Prg_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Prg_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Prg_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Prg_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Prg_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def rand(self):
		return Prg_rand(self.objhandle)
	def srand(self, aSeed):
		Prg_srand(self.objhandle, c_int(aSeed))

class Sfxr(object):
	HURT = 4
	LASER = 1
	BLIP = 6
	JUMP = 5
	COIN = 0
	EXPLOSION = 2
	POWERUP = 3
	def __init__(self):
		self.objhandle = Sfxr_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Sfxr_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Sfxr_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Sfxr_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Sfxr_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def reset_params(self):
		Sfxr_resetParams(self.objhandle)
	def load_params(self, aFilename):
		return Sfxr_loadParams(self.objhandle, c_char_p(aFilename))
	def load_preset(self, aPresetNo, aRandSeed):
		return Sfxr_loadPreset(self.objhandle, c_int(aPresetNo), c_int(aRandSeed))
	def set_looping(self, aLoop):
		Sfxr_setLooping(self.objhandle, c_int(aLoop))
	def set_filter(self, aFilterId, aFilter):
		Sfxr_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def stop(self):
		Sfxr_stop(self.objhandle)

class Speech(object):
	def __init__(self):
		self.objhandle = Speech_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Speech_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Speech_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Speech_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Speech_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def set_text(self, aText):
		return Speech_setText(self.objhandle, c_char_p(aText))
	def set_looping(self, aLoop):
		Speech_setLooping(self.objhandle, c_int(aLoop))
	def set_filter(self, aFilterId, aFilter):
		Speech_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def stop(self):
		Speech_stop(self.objhandle)

class Wav(object):
	def __init__(self):
		self.objhandle = Wav_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		Wav_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		Wav_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		Wav_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		Wav_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def load(self, aFilename):
		return Wav_load(self.objhandle, c_char_p(aFilename))
	def load_mem(self, aMem, aLength):
		return Wav_loadMem(self.objhandle, POINTER(c_ubyte)(aMem), c_uint(aLength))
	def get_length(self):
		return Wav_getLength(self.objhandle)
	def set_looping(self, aLoop):
		Wav_setLooping(self.objhandle, c_int(aLoop))
	def set_filter(self, aFilterId, aFilter):
		Wav_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def stop(self):
		Wav_stop(self.objhandle)

class WavStream(object):
	def __init__(self):
		self.objhandle = WavStream_create()
	def __enter__(self):
		return self
	def __exit__(self, eType, eValue, eTrace):
		WavStream_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
		return False
	def close(self):
		WavStream_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def destroy(self):
		WavStream_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def quit(self):
		WavStream_destroy(self.objhandle)
		self.objhandle = c_void_p(0)
	def load(self, aFilename):
		return WavStream_load(self.objhandle, c_char_p(aFilename))
	def get_length(self):
		return WavStream_getLength(self.objhandle)
	def set_looping(self, aLoop):
		WavStream_setLooping(self.objhandle, c_int(aLoop))
	def set_filter(self, aFilterId, aFilter):
		WavStream_setFilter(self.objhandle, c_uint(aFilterId), aFilter.objhandle)
	def stop(self):
		WavStream_stop(self.objhandle)
