Downloads
=========

This page lists SoLoud downloads, as well as other relevant information.

Latest stable release
---------------------
[soloud_20150512.zip](soloud_20150512.zip) <<- Download here

Documentation: [PDF](soloud_20150512.pdf) | [EPUB](soloud_20150512.epub) | [MOBI](soloud_20150512.mobi) | [HTML](soloud_20150512.html) 

Milestones
----------
SoLoud milestones are named after the ITU radio band symbols.

![Milestone symbols](images/milestones)\ 

Some milestone hilights: 

- LF is planned
- VLF is under construction
- ULF went all 3d audio, and added more foreign interfaces
- SLF put in playClocked, voice groups and python support
- ELF added libmodplug, sfxr and "C" api generator
- TLF had mixing busses, visualization data, and various backends

Development
-----------
You can find the latest, bleeding-edge version on GitHub at: <https://github.com/jarikomppa/soloud>. Note that the latest development version may be unstable.

There's a mailing list at <http://groups.google.com/d/forum/soloud>

Finally, there's #soloud on ircnet, if you want to pop by.

Swag
----
Yes, someone asked. So, you can buy SoLoud swag here: <http://solstuff.spreadshirt.fi/>

Additional files
----------------
[timgm6mb_pat.zip](timgm6mb_pat.zip) Free MIDI patches for the libmodplug .mid / .abc playing (around 11MB zip) by [http://www.timbrechbill.com](http://www.timbrechbill.com), converted from sf2 to .pat files with [http://alsa.opensrc.org/Unsf](unsf).

    "I created some of the samples myself and all others are either public 
    domain or fall under the terms of the GNU General Public License." 
    -- Tim Brechbill - http://www.timbrechbill.com


Release history
---------------

[soloud_20150512.zip](soloud_20150512.zip) 

Documentation: [PDF](soloud_20150512.pdf) | [EPUB](soloud_20150512.epub) | [MOBI](soloud_20150512.mobi) | [HTML](soloud_20150512.html) 

- SoLoud "VLF" release
- Hilights:
    - Virtual voices - play 1000 voices, SoLoud will figure out which ones you hear
    - Major documentation update
        - yEd graphs
        - New web layout
        - Many tweaks to PDF layout
        - PDF doc is now 141 pages (ULF release had 94)
        - Single-file HTML now contains images        
    - New backend: ALSA for Linux
    - New filter: bassboost
    - New backend: Null driver 
        - No audio device, call mix() to pull samples.
    - New demo: virtualvoices
    - New demo: null driver
    - New demo: enumerate
    - Added functions to query information on currently active back-end
    - Added get/setLooping for live sounds
    - Added default volume for audio sources
    - Added custom 3d attenuator interface
    - Added LEFT_HANDED_3D flag for left-handed 3d coordinate processing
    - Added setInaudibleBehavior
    - Split demo common code to a separate static lib
    - Upped filter count to 8        
    - Some x64 fixes
    - "nondyn" naming removed, calling static libs static now
    - Removed modf in monotone because Linux clib didn't like it
    - Cleanup fix - call stop() from all audio source virtual dtors
    - Memory file bugfixes
    - Wav file loading was broken after move to File interface, fixed
    - Some div by zeros fixed in Sfxr    
    - 3d processing done largely outside audio mutex
        - Plus side - 3d stuff is way more performant
        - Minus side - 3d stuff isn't thread safe
    - And a bunch of smaller bug fixes and tweaks
    

[soloud_20150427.zip](soloud_20150427.zip) 

Documentation: [PDF](soloud_20150427.pdf) | [EPUB](soloud_20150427.epub) | [MOBI](soloud_20150427.mobi) | [HTML](soloud_20150427.html) 

- Hilights:   
    - More demos moved to new framework, features added
    - Switched FFT implementations
    - 'FFTFilter' is now base class for STFT filters
    - Generalized file i/o through File class
    - New interface to query info from live audio streams
    - Commodore plus/4 TED and Commodore 64 SID song support
    - As always, documentation updates and little bug fixes here and there. 

[soloud_20150419.zip](soloud_20150419.zip)

Documentation: [PDF](soloud_20150419.pdf) | [EPUB](soloud_20150419.epub) | [MOBI](soloud_20150419.mobi) | [HTML](soloud_20150419.html) 

- Not a milestone release, just a refresher
- Hilights:   
    - Moved from premake4 to premake fork GENie for build file generation
    - SDL2 static linking support
    - MONOTONE tracker replayer
        - New demo: monotone
    - New filter: DC removal
    - New demo framework based on ImGui, simplifies demo code and makes demos prettier
    - More foreign interfaces
        - D
        - GameMaker:Studio
    - Updated versions of libmodplug and stb_vorbis
    - Documentation updates and little bug fixes here and there.    

[soloud_20140821.zip](soloud_20140821.zip)

Documentation: [PDF](soloud_20140821.pdf) | [EPUB](soloud_20140821.epub) | [MOBI](soloud_20140821.mobi) | [HTML](soloud_20140821.html) 

- SoLoud "ULF" release
- Hilights:
    - 3d (positional) audio interfaces
        - Including positions, doppler, etc
        - New demo: 3dtest, a simple test of the positional audio
    - More foreign interfaces
        - BlitzMax 
        - Ruby
        - RPG Maker 
        - c# (c sharp)
    - Lots more documentation and little bug fixes here and there.    

[soloud_20140622.zip](soloud_20140622.zip)

Documentation: [PDF](soloud_20140622.pdf) | [EPUB](soloud_20140622.epub) | [MOBI](soloud_20140622.mobi) | [HTML](soloud_20140622.html) 

- SoLoud "SLF" release
- Hilights:
    - New demo: "space", demonstrating visualization data from different parts of the pipeline
    - New demo: "pew pew", demonstrating difference between play() and playClocked()
    - New filter: flanger
    - New way to play sounds: playClocked() for rapidly-launched sounds, to make it so all sounds don't start from the beginning of a sound buffer
    - Loop count query added    
    - Voice groups to command several voices in one atomic operation
- A lot of variable type changes:
    - Defined error codes, and several functions return error codes now.
    - Time variable type changed from float to double
    - Typedefs for handles, time, result codes
    - Plenty of "int" -> "unsigned int" changes, some ints changed to bools
- A lot of work on code generation and wrappers:
    - Codegen now also outputs soloud_codegen.py with all data needed to generate wrappers
    - Python wrapper generator
    - Python API
- Other changes that affect your code:
    - stopSound() renamed to stopAudioSource(). Audio sources also got a new stop() function that stops all instances.
    - Echo filter now has an optional low pass filter to make more "natural" echoes
    - Default post-clip scaler upped from 0.5 to 0.95
    - New songs for multimusic, changed multimusic to use voice groups
- Regarding builds:
    - Redesigned the mechanism by which different backends are included in the build, controlled mainly through premake
    - Many new premake options    
    - "nondyn" SDL build added which links to SDL directly, for special needs such as emscripten
    - sdl2 dll may work now (mutex functions were renamed from SDL to SDL2, audio API should be almost the same)
- And, under the hood:
    - Side project - resamplerlab - to make writing new resamplers easier, with some experimental resamplers
    - Some work towards osx, linux compatibility
    - FFT code moved to its own source so it can be more easily replaced in the future
    - Changed mixer fixed point from 16.16 to 12.20
    - Various small fixes, as usual.

[soloud_20140521.zip](soloud_20140521.zip) 

Documentation: [PDF](soloud_20140521.pdf) | [EPUB](soloud_20140521.epub) | [MOBI](soloud_20140521.mobi) | [HTML](soloud_20140521.html) 

- SoLoud "ELF" release
- Critical bug fix: process was sometimes left hanging at application quit.
- Audio instance creation moved outside the audio thread mutex (some instance creation may take quite a bit of time, causing stutter)
- Wav/wavstream now can report length of the stream in seconds via getLength()
- Filter interface has simplified parameter handling to make writing new filters easier
- Lo-fi filter
- Libmodplug audio source for various formats (669, abc, amf, ams, dbm, dmf, dsm, far, it, j2b, mdl, med, mid, mod, mt2, mtm, okt, pat, psm, ptm, s3m, stm, ult, umx, xm, as well as wider support for wav files).
- SFXR audio source for old school sound effects
- Greatly simplified init pattern; no need (if you don't want) to care about which back-end to use
- Dynamic linking of most back-ends
- "C" API code generator
- DLL based on the "C" API
- Misc smaller fixes, cppcheck fixes and reorganization

[soloud_20131109.zip](soloud_20131109.zip) 

Documentation: [PDF](soloud_20131109.pdf) | [EPUB](soloud_20131109.epub) | [MOBI](soloud_20131109.mobi) | [HTML](soloud_20131109.html) 

- SoLoud "TLF" release 
- PortAudio, winmm, oss, wasapi, xaudio2 and openal back-ends
- Simplified cleanup - no separate cleanup functions per back-end
- Simple cross-platform thread support for back-ends that require it
- Filter interface revamped
- Echo, fft and biquad resonant (low/high/bandpass) filters
- Switched from ffft to a simpler (and slower) fft implementation
- Faders can now oscillate
- wav/ogg files can be loaded from memory 
- AudioInstance -> AudioSourceInstance rename
- SoLoud core split into a bunch of source files to keep things manageable
- Various changes aiming at multi-channel support; hard-coded stereo support removed
- Audio samples no longer interlaced to simplify filter processing
- Simplified init and wave loading by removing useless options or moving them to constants in soloud.h
- Mixing busses implemented
- Visualization via FFT or waveform supported, requires init flag to work
- Resampler interface and linear resampler
- Granularity of audio buffers fixed to a small value, configurable via soloud.h
- Per-sample volume faders
- Reworked old and added more example applications
- Premake4 script for project files to generate static libraries
- Reorganized files for easier handling (single include directory, etc)
- Lots and lots and lots of bug fixes and mixer rewrites


[soloud_20130808.zip](soloud_20130808.zip)

- They grow so fast! Hilights:
- Redesigned, simpler filter system. Probably still needs a lot of work.
- Added a FFT library and calls to get FFT data from SoLoud. This can be disabled via a #define to improve compile time.
- Added stopSound() to stop all instances of a sound. This is also called from the dtor of audio sources for simpler application cleanup.
- Tweaked and improved all demos.
- Volume faders are calculated on per-sample basis instead of per-buffer, this removed plenty of noise.
- Added getPan.
- and various bugfixes and CppCheck fixes.

[soloud_20130801.zip](soloud_20130801.zip)

- Initial release. If you're after something really minimalistic, dig in.

The package contains all sources, and pre-compiled win32 binaries. The sources should(tm) be portable to other platforms.

