Downloads
=========

This page lists SoLoud downloads, as well as other relevant information.

Development
-----------
You can find the latest, bleeding-edge version on GitHub at: <https://github.com/jarikomppa/soloud>. Note that the latest development version may be unstable.

There's a mailing list at <http://groups.google.com/d/forum/soloud>

Finally, there's #soloud on ircnet, if you want to pop by.

Swag
----
Yes, someone asked. So, you can buy SoLoud swag here: <http://solstuff.spreadshirt.fi/>

Additional files
----------------
[timgm6mb_pat.zip](timgm6mb_pat.zip) Free MIDI patches for the libmodplug .mid / .abc playing (around 11MB zip) by [http://www.timbrechbill.com](http://www.timbrechbill.com), converted from sf2 to .pat files with [http://alsa.opensrc.org/Unsf](unsf).

    "I created some of the samples myself and all others are either public 
    domain or fall under the terms of the GNU General Public License." 
    -- Tim Brechbill - http://www.timbrechbill.com


Stable Releases 
--------------- 

[soloud_20140521.zip](soloud_20140521.zip) <<- Download here

Documentation: [PDF](soloud_20140521.pdf) | [EPUB](soloud_20140521.epub) | [MOBI](soloud_20140521.mobi) | [HTML](soloud_20140521.html) 

- SoLoud "ELF" release
- Critical bug fix: process was sometimes left hanging at application quit.
- Audio instance creation moved outside the audio thread mutex (some instance creation may take quite a bit of time, causing stutter)
- Wav/wavstream now can report length of the stream in seconds via getLength()
- Filter interface has simplified parameter handling to make writing new filters easier
- Lo-fi filter
- Libmodplug audio source for various formats (669, abc, amf, ams, dbm, dmf, dsm, far, it, j2b, mdl, med, mid, mod, mt2, mtm, okt, pat, psm, ptm, s3m, stm, ult, umx, xm, as well as wider support for wav files).
- SFXR audio source for old school sound effects
- Greatly simplified init pattern; no need (if you don't want) to care about which back-end to use
- Dynamic linking of most back-ends
- "C" API code generator
- DLL based on the "C" API
- Misc smaller fixes, cppcheck fixes and reorganization

[soloud_20131109.zip](soloud_20131109.zip) 

Documentation: [PDF](soloud_20131109.pdf) | [EPUB](soloud_20131109.epub) | [MOBI](soloud_20131109.mobi) | [HTML](soloud_20131109.html) 

- SoLoud "TLF" release 
- PortAudio, winmm, oss, wasapi, xaudio2 and openal back-ends
- Simplified cleanup - no separate cleanup functions per back-end
- Simple cross-platform thread support for back-ends that require it
- Filter interface revamped
- Echo, fft and biquad resonant (low/high/bandpass) filters
- Switched from ffft to a simpler (and slower) fft implementation
- Faders can now oscillate
- wav/ogg files can be loaded from memory 
- AudioInstance -> AudioSourceInstance rename
- SoLoud core split into a bunch of source files to keep things manageable
- Various changes aiming at multi-channel support; hard-coded stereo support removed
- Audio samples no longer interlaced to simplify filter processing
- Simplified init and wave loading by removing useless options or moving them to constants in soloud.h
- Mixing busses implemented
- Visualization via FFT or waveform supported, requires init flag to work
- Resampler interface and linear resampler
- Granularity of audio buffers fixed to a small value, configurable via soloud.h
- Per-sample volume faders
- Reworked old and added more example applications
- Premake4 script for project files to generate static libraries
- Reorganized files for easier handling (single include directory, etc)
- Lots and lots and lots of bug fixes and mixer rewrites


[soloud_20130808.zip](soloud_20130808.zip)

- They grow so fast! Hilights:
- Redesigned, simpler filter system. Probably still needs a lot of work.
- Added a FFT library and calls to get FFT data from SoLoud. This can be disabled via a #define to improve compile time.
- Added stopSound() to stop all instances of a sound. This is also called from the dtor of audio sources for simpler application cleanup.
- Tweaked and improved all demos.
- Volume faders are calculated on per-sample basis instead of per-buffer, this removed plenty of noise.
- Added getPan.
- and various bugfixes and CppCheck fixes.

[soloud_20130801.zip](soloud_20130801.zip)

- Initial release. If you're after something really minimalistic, dig in.

The package contains all sources, and pre-compiled win32 binaries. The sources should(tm) be portable to other platforms.

