## Frequently Asked Questions


### What does it play?


Currently, SoLoud includes support for uncompressed 8 and 16 bit RIFF
Wav files, as well as Ogg Vorbis files. Both of these only support a
limited feature set of said formats, so you may experience some issues
with strange files.

Additionally, SoLoud comes with a speech synthesizer based on rsynth
and a retro sound effect synthesizer Sfxr, replayer for MONOTONE 
PC-speaker tracker music and a replayer for C64 SID and Commodore plus/4 TED music.

Finally, SoLoud includes libmodplug, through which it can play 669, abc, 
amf, ams, dbm, dmf, dsm, far, it, j2b, mdl, med, mid, mod, mt2, mtm, okt, 
pat, psm, ptm, s3m, stm, ult, umx, xm, as well as wider support for wav 
files than the stand-alone wav audio source. (Due to the size of 
libmodplug, SoLoud can be compiled without it).

The interface for audio sources is relatively simple, so new formats and
noise generators, as well as audio filters, can be made.

An example sin/saw/triangle/square generator is also available, as part
of the "piano" example.

All of the above can also be fed through series of filters for additional
fun.

### What dependencies does it have?


There's no external library dependencies (apart from stdlib). However,
to get audio out of your speakers, a back-end is needed. Back-ends that
currently exist include SDL, windows multimedia, oss, alsa and portaudio, 
and SoLoud has been designed so that making new back-ends would be as
painless as possible.

### Is there a DLL / C-Interface?


Yes! This DLL can be used from non-c++ environments through the "C" interface. SoLoud comes with wrappers for Python, Ruby, c#, BlitzMax and others.

### What's the animal in the logo?


A fennec fox. Google it. They're cute!

### Is there a mailing list?


There's a google group, at <http://groups.google.com/d/forum/soloud>

Main development occurs on GitHub, at
<https://github.com/jarikomppa/soloud> and the issue tracker is in use.

Finally, there's #soloud on ircnet, if you want to pop by.

### No doxygen docs?


No, instead you get documentation written by an actual human being. Granted, 
some function descriptions may be a bit terse or repetitive, but that's what 
you would have gotten from doxygen too..

### Why not use this superior fork of libmodplug?


I'm aware there are other forks of libmodplug, which may be in better shape than the one
used in SoLoud by default. However, those forks use more restrictive licenses, which
(while still liberal) would require changes in SoLoud licensing. At the moment, you
don't need to mention the use of SoLoud anywhere if you don't want to.

That said, nothing's stopping you from compiling a version of SoLoud that uses another
fork of libmodplug.

### Can SoLoud do HRTF?

Currently, no. Pull requests are welcome =)

### What about surround speakers?

Currently, no. Support is planned in a future milestone, however.

### Are these real questions?


Surprisingly, yes.
