# Foreign Interfaces

SoLoud can be used from various environments through a "C" API DLL.

In order to use SoLoud from a different environment, such as Python or BlitzMax, 
you need the SoLoud DLL and a wrapper. The wrappers for SoLoud are not made
by hand, but instead generated through Python scripts. This minimizes hassle
when SoLoud gets new features, as the new wrappers can simply be generated via
the scripts.
