Legal
=====

SoLoud, [like everything else](http://everythingisaremix.info/), stands on the shoulders of giants;
however, care has been taken to only incorporate source code that is
under liberal licenses, namely ZLib/LibPNG, CC0 or public domain, or
similar, like WTFPL or Unlicense, where you don't need to include
mention of the code in your documentation or splash screens or any such
nonsense.

SoLoud Proper
-------------

SoLoud proper is licensed under the ZLib/LibPNG license. The code is a
clean-room implementation with no outside sources used.

    SoLoud audio engine
    Copyright (c) 2013 Jari Komppa

    This software is provided 'as-is', without any express or implied
    warranty. In no event will the authors be held liable for any damages
    arising from the use of this software.

    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:

       1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.

       2. Altered source versions must be plainly marked as such, and must 
       not be misrepresented as being the original software.

       3. This notice may not be removed or altered from any source
       distribution.

OGG Support
-----------

The OGG support in the Wav and WavStream sound sources is based on
stb_vorbis by Sean Barrett, and it's in the public domain. You can find
more information (and latest version) at
<http://nothings.org/stb_vorbis/>

Speech Synthesizer
------------------

The speech synth is based on rsynth by the late Nick Ing-Simmons (et
al). He described the legal status as:

        This is a text to speech system produced by
        integrating various pieces of code and tables
        of data, which are all (I believe) in the
        public domain.

Since then, the rsynth source code has passed legal checks by several
open source organizations, so it "should" be pretty safe.

The primary copyright claims seem to have to do with text-to-speech
dictionary use, which I've removed completely.

I've done some serious refactoring, clean-up and feature removal on the
source, as all I need is "a" free, simple speech synth, not a "good"
speech synth. Since I've removed a bunch of stuff, this is probably
safer public domain release than the original.

I'm placing my changes in public domain as well, or if that's not
acceptable for you, then CC0:
<http://creativecommons.org/publicdomain/zero/1.0/>.

The SoLoud interface files (soloud_speech.\*) are under the same
ZLib/LibPNG license as the other SoLoud bits.

Fast Fourier Transform (FFT)
----------------------------

FFT calculation is provided by a fairly simpple implementation by
Stephan M. Bernsee, under the Wide Open License:

    COPYRIGHT 1996 Stephan M. Bernsee <smb [AT] dspdimension [DOT] com>

                            The Wide Open License (WOL)

    Permission to use, copy, modify, distribute and sell this software and its
    documentation for any purpose is hereby granted without fee, provided that
    the above copyright notice and this license appear in all source copies. 
    THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY OF
    ANY KIND. See http://www.dspguru.com/wol.htm for more information.

Sfxr
----

The sfxr sound effects synthesizer is by Tomas Pettersson, re-licensed under
zlib/libpng license by permission.

    Copyright (c) 2014 Jari Komppa
    Based on code (c) by Tomas Pettersson, re-licensed under zlib by permission
    
    This software is provided 'as-is', without any express or implied
    warranty. In no event will the authors be held liable for any damages
    arising from the use of this software.
    
    Permission is granted to anyone to use this software for any purpose,
    including commercial applications, and to alter it and redistribute it
    freely, subject to the following restrictions:
    
       1. The origin of this software must not be misrepresented; you must not
       claim that you wrote the original software. If you use this software
       in a product, an acknowledgment in the product documentation would be
       appreciated but is not required.
    
       2. Altered source versions must be plainly marked as such, and must not be
       misrepresented as being the original software.
    
       3. This notice may not be removed or altered from any source
       distribution.

Libmodplug
----------

The branch of libmodplug that is used in SoLoud was declared public domain.
Authors include:

- Olivier Lapicque - <olivierl@jps.net>
- Markus Fick - <webmaster@mark-f.de>
- Adam Goode - <adam@evdebs.org>
- Jake Stine - <air@divent.org>
- Peter Grootswagers - <pgrootswagers@planet.nl>
- Marco Trillo - <toad@arsystel.com>
- Kenton Varda - <temporal@gauge3d.org>

with some fixes modifications by Jari Komppa, to work with SoLoud.
