Premake
=======

SoLoud comes with a premake4 script. If you want to build SoLoud as static library, instead of including the source files in your project, this can be handy.

Premake can be downloaded from <http://industriousone.com/premake>.

Unfortunately, premake4 cannot magically figure out where your libraries may be installed, so you may have to edit the premake4.lua file. The lines to edit can be found at the very beginning of the file, with the following defaults:

    local sdl_root       = "/libraries/sdl"
    local portmidi_root  = "/libraries/portmidi"
    local dxsdk_root     = "C:/Program Files (x86)/Microsoft ..."
    local portaudio_root = "/libraries/portaudio"
    local openal_root    = "/libraries/openal"

You will most likely want to edit at least the sdl_root variable. After your edits, you can run premake4 to generate makefiles or the IDE project files of your preference, such as:

    premake4 vs2010
    
The current version (4.3) supports codeblocks, codelite, vs2002, vs2003, vs2005, vs2008, vs2010, xcode3 and gnu makefiles 
(gmake). New version with at least vs2012 support is coming soon (I hope).

You can also use one or more of the optional parameters to change the build behavior. 

Option                Description
-------------------   -----------
with-libmodplug       Include libmodplug in build
with-native-only      Only native backends (winmm/oss) in build
with-portmidi         Use portmidi to drive midi keyboard in the piano demo
with-sdl-only         Only include sdl in build
with-sdlnondyn-only   Only include sdl that doesn't use dyndll in build
with-tools            Include (optional) tools in build
with-xaudio2          Include xaudio2 in build

So for example, in order to build SoLoud with libmodplug and tools on vs2010, use:

    premake4 --with-libmodplug --with-tools vs2010 
    